package pdf

import (
	"fmt"
	"time"

	"github.com/jung-kurt/gofpdf"
)

type ReportData struct {
	PodCosts     []PodCost
	TotalCost    float64
	HardwareCost float64
	ElecCost     float64
	Nodes        []NodeInfo
	GeneratedAt  time.Time
}

type PodCost struct {
	Name      string
	Namespace string
	CPU       string
	Memory    string
	Cost      float64
}

type NodeInfo struct {
	Name         string
	MemoryGB     float64
	HardwareCost float64
	ElecCost     float64
	TotalCost    float64
}

func Generate(data ReportData, filename string) error {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetTitle("kfin Cost Report", false)
	pdf.AddPage()

	// Title
	pdf.SetFont("Arial", "B", 24)
	pdf.Cell(190, 20, "kfin Cost Analysis Report")
	pdf.Ln(12)

	// Date
	pdf.SetFont("Arial", "I", 10)
	pdf.Cell(190, 8, fmt.Sprintf("Generated: %s", data.GeneratedAt.Format("2006-01-02 15:04")))
	pdf.Ln(15)

	// Summary section
	pdf.SetFont("Arial", "B", 16)
	pdf.Cell(190, 10, "Cost Summary")
	pdf.Ln(10)

	pdf.SetFont("Arial", "", 12)
	pdf.Cell(100, 8, "Hardware (amortized):")
	pdf.Cell(90, 8, fmt.Sprintf("$%.2f/month", data.HardwareCost))
	pdf.Ln(8)

	pdf.Cell(100, 8, "Electricity:")
	pdf.Cell(90, 8, fmt.Sprintf("$%.2f/month", data.ElecCost))
	pdf.Ln(8)

	pdf.SetFont("Arial", "B", 12)
	pdf.Cell(100, 8, "Total Monthly Cost:")
	pdf.Cell(90, 8, fmt.Sprintf("$%.2f/month", data.TotalCost))
	pdf.Ln(15)

	// Node breakdown
	pdf.SetFont("Arial", "B", 16)
	pdf.Cell(190, 10, "Node Costs")
	pdf.Ln(10)

	// Table header
	pdf.SetFont("Arial", "B", 10)
	pdf.Cell(60, 8, "Node")
	pdf.Cell(40, 8, "Memory")
	pdf.Cell(45, 8, "Hardware")
	pdf.Cell(45, 8, "Electricity")
	pdf.Ln(8)
	pdf.Line(pdf.GetX(), pdf.GetY(), 190, pdf.GetY())
	pdf.Ln(4)

	pdf.SetFont("Arial", "", 10)
	for _, node := range data.Nodes {
		pdf.Cell(60, 7, node.Name)
		pdf.Cell(40, 7, fmt.Sprintf("%.1f GB", node.MemoryGB))
		pdf.Cell(45, 7, fmt.Sprintf("$%.2f", node.HardwareCost))
		pdf.Cell(45, 7, fmt.Sprintf("$%.2f", node.ElecCost))
		pdf.Ln(7)
	}
	pdf.Ln(10)

	// Pod costs
	pdf.SetFont("Arial", "B", 16)
	pdf.Cell(190, 10, "Pod Costs")
	pdf.Ln(10)

	// Table header
	pdf.SetFont("Arial", "B", 9)
	pdf.Cell(50, 8, "Pod")
	pdf.Cell(35, 8, "Namespace")
	pdf.Cell(30, 8, "CPU")
	pdf.Cell(35, 8, "Memory")
	pdf.Cell(40, 8, "Cost")
	pdf.Ln(8)
	pdf.Line(pdf.GetX(), pdf.GetY(), 190, pdf.GetY())
	pdf.Ln(4)

	pdf.SetFont("Arial", "", 8)
	for _, pod := range data.PodCosts {
		if pod.Cost > 0 {
			pdf.Cell(50, 6, truncate(pod.Name, 25))
			pdf.Cell(35, 6, truncate(pod.Namespace, 15))
			pdf.Cell(30, 6, pod.CPU)
			pdf.Cell(35, 6, pod.Memory)
			pdf.Cell(40, 6, fmt.Sprintf("$%.2f", pod.Cost))
			pdf.Ln(6)
		}
	}

	// Footer
	pdf.SetY(-20)
	pdf.SetFont("Arial", "I", 8)
	pdf.Cell(190, 5, "Generated by kfin - Kubernetes Cost Analyzer")

	return pdf.OutputFileAndClose(filename)
}

func truncate(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen]
}
